# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  VmImage:ubuntu-latest

steps:
 - script: echo "started devops"
   displayName: 'start'

 - script: bash script.sh
   displayName: 'run script'

 - script: echo "Pipeline completed"
   displayName: 'End' 
