# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "this is building"
      displayName: 'shit'

- stage: Test
  jobs:
   - job: Test
     steps:
     - script: echo "this is test"
       displayName: 'yeah'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo "this is deploy"
      displayName: 'deploying'
